{{alias}}
shadowsock      = +forward-override{forward-socks5 127.0.0.1:1025 .}
#需要经常更换代理IP,如果代理IP没有问题破解不了只有两种情况
#1.采用https检测验证，这就需要自己找出验证网址使用acl文件放行
#2.检测验证地址变动
copyright         = +forward-override{forward-socks5 127.0.0.1:1025 58.240.53.194:80}
default     = shadowsock
#==========默认代理==========
{default}
/
#==========破解版权==========
{copyright} 
#腾讯视频
vv.video.qq.com
#网易云音乐
music.163.com
nstool.netease.com
music.httpdns.c.163.com
#哔哩哔哩
.bilibili.com
#===========================